spring:
  profiles:
    active: dev
  application:
    name: sickday_backend
  config:
    import: configserver:${CONFIG_HOST:http://176.113.82.235}:${CONFIG_PORT:8888}
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 5000
  jackson:
    default-property-inclusion: non_null